services:
  - type: web
    name: jsongrid
    env: static
    buildCommand: pnpm install && pnpm build
    staticPublishPath: ./dist
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-cache
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
